server:
  port: 8081


spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: coupon-template
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/coupon?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    hikari:
      connection-test-query: select 1
      minimum-idle: 5
      maximum-pool-size: 50
    password: 123456

pagehelper:
  reasonable: true

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: org/example/**/*.xml